import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/Home.module.scss'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <Link href='/registro'>
            <div className={styles.card}>
              <h2>Registro &rarr;</h2>
              <p>Prueba de ruta del registro</p>
            </div>
          </Link>

          <Link href='/usuario'>
            <div className={styles.card}>
              <h2>Dashboard &rarr;</h2>
              <p>Prueba de ruta a la zona de usuario</p>
            </div>
          </Link>

          <Link href='/test-page'>
            <div className={styles.card}>
              <h2>Test page &rarr;</h2>
              <p>Prueba de ruta a la pagina de pruebas</p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
