export interface PostFormCompany {
  webform_id: string
  activos: string
  activos_2022: string
  activos_2023: string
  archivos: string[]
  cargo: string
  categoria: string[]
  celular: string
  ciudad_de_residencia: string
  cobertura_alcance_proyecto: string
  correo: string
  departamento_de_residencia: string
  descripcion_de_producto_servicio: string
  de_que_trata_el_proyecto: string
  exportaciones: string
  exportaciones_2022: string
  exportaciones_2023: string
  importaciones: string
  importaciones_2022: string
  importaciones_2023: string
  indicadores_de_gestion: string
  direccion: string
  nit: string
  nombre_completo: string
  nombre_del_proyecto: string
  numero_de_documento: string
  pasivos: string
  pasivos_2022: string
  pasivos_2023: string
  patrimonio: string
  patrimonio_2022: string
  patrimonio_2023: string
  por_que_proyecto_premiado: string
  quien_contactar: string
  telefono: string
  tiempo_desarrollado_proyecto: string
  utilidades: string
  utilidades_2022: string
  utilidades_2023: string
  ventas: string
  ventas_2022: string
  ventas_2023: string
}
